name: Pull request

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/upload-artifact@v4
        id: plugin-upload
        with:
          name: 'tpay-magento2-graphql'
          path: './'

      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            Tpay Magento2 GraphQL plugin - ${{ steps.plugin-upload.outputs.artifact-url }}
      
